import Head from 'next/head';
import Hero from '../components/Hero';

export default function Home() {
  return (
     <div> 
      <Head>
        <a href='/#'><title>Exotic</title></a>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero heading='Home' message='Want to learn about copyright-free images ? Click on Learn More button.'/>
    </div>
  );
}
